require("holmes.cmp")
require("holmes.colors")
require("holmes.comment")
require("holmes.harpoon")
-- require("holmes.lsp")
require("holmes.lualine")
require("holmes.neo-tree")
require("holmes.nvim-autopairs")
require("holmes.plugins")
require("holmes.remap")
require("holmes.set")
require("holmes.telescope")
require("holmes.toggleterm")
require("holmes.treesitter")

-- add lsp folder
require("holmes.lsp")
